export const salonContent = [
    {
      cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
      star: require("../../assets/images/SalonsPageImages/star.png"),
      ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
      mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
      chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
      name: "Athena Hair Salon & Unisex Spa",
      rating: 4.8,
      ratingsCount: 1361,
      location: "Windmills Road, Bengaluru",
      distance: "570 m",
      services: [
        { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
      ],
    },
    {
      cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
      star: require("../../assets/images/SalonsPageImages/star.png"),
      ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
      mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
      chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
      name: "Athena Hair Salon & Unisex Spa",
      rating: 4.8,
      ratingsCount: 1361,
      location: "Windmills Road, Bengaluru",
      distance: "570 m",
      services: [
        { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
      ],
    },
    {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
      {
        cardImage: require("../../assets/images/SalonsPageImages/cardImage.png"),
        star: require("../../assets/images/SalonsPageImages/star.png"),
        ellipse: require("../../assets/images/SalonsPageImages/Ellipse.png"),
        mapPin: require("../../assets/images/SalonsPageImages/map-pin.png"),
        chevronRight: require("../../assets/images/SalonsPageImages/chevron-right.png"),
        name: "Athena Hair Salon & Unisex Spa",
        rating: 4.8,
        ratingsCount: 1361,
        location: "Windmills Road, Bengaluru",
        distance: "570 m",
        services: [
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
          { name: "Hair cut ladies", timing: "1 hr 15 mins", price: "₹599" },
        ],
      },
  ];